//show actions
export const FETCH_SHOWS = 'FETCH_SHOWS';
export const FETCH_SHOW_DETAILS = 'FETCH_SHOW_DETAILS';
export const GET_WATCHLIST = 'GET_WATCHLIST';

//search actions
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';

//season actions
export const FETCH_SEASON_EPISODES = 'FETCH_SEASON_EPISODES';
export const CLEAR_FETCHED_EPISODE = 'CLEAR_FETCHED_EPISODE';

//episode actions
export const FETCH_WATCHED_EPISODES = 'FETCH_WATCHED_EPISODES'
export const ADD_EPISODE_TO_WATCHLIST = 'ADD_EPISODE_TO_WATCHLIST';
export const DELETE_EPISODE_FROM_WATCHLIST = 'DELETE_EPISODE_FROM_WATCHLIST';

//user actions 
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CREATE_USER = 'CREATE_USER';
export const ADD_SHOW_TO_WATCHLIST = 'ADD_SHOW_TO_WATCHLIST';
export const DELETE_SHOW_FROM_WATCHLIST = 'DELETE_SHOW_FROM_WATCHLIST';

//actor actions
export const FETCH_ACTOR_DETAILS = 'FETCH_ACTOR_DETAILS';
export const RESET_ACTOR_DETAILS = 'RESET_ACTOR_DETAILS';

//mixed actions
export const RESET_SHOW_PAGE = 'RESET_SHOW_PAGE';